spring:
  application:
    name: medicare-api
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/medicare_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

