import { ArrowRight, CalendarCheck, ShieldCheck, Stethoscope, Users, Building2, HeartPulse } from 'lucide-react'
import { Link } from 'react-router-dom'
import { departments, doctors } from '../../data/site'
import heroImage from '../../assets/medicare-hero.png'
const stats = [['25+', 'Years of care'], ['50+', 'Specialist doctors'], ['20k+', 'Happy patients'], ['24/7', 'Emergency support']]
export default function HomePage(){return <>
 <section className="overflow-hidden bg-gradient-to-br from-brand-50 via-white to-cyan-50 dark:from-slate-950 dark:via-slate-950 dark:to-slate-900"><div className="container-page grid min-h-[560px] items-center gap-12 py-16 lg:grid-cols-2"><div><p className="mb-4 inline-flex items-center gap-2 rounded-full bg-blue-100 px-3 py-1 text-sm font-semibold text-brand-600"><HeartPulse size={16}/> Trusted healthcare partner</p><h1 className="text-4xl font-bold leading-tight tracking-tight text-slate-900 dark:text-white sm:text-6xl">Better care, <span className="text-brand-600">closer to home.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600 dark:text-slate-300">Exceptional medical care from experienced specialists, with every detail designed around you.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/appointments" className="btn-primary">Book an appointment <ArrowRight className="ml-2" size={18}/></Link><Link to="/doctors" className="btn-secondary">Find a doctor</Link></div><div className="mt-9 flex gap-6 text-sm text-slate-600 dark:text-slate-300"><span className="flex items-center gap-2"><ShieldCheck size={18} className="text-brand-600"/> Trusted specialists</span><span className="flex items-center gap-2"><CalendarCheck size={18} className="text-brand-600"/> Easy booking</span></div></div><div className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-4 rounded-[2.5rem] bg-brand-500/15 blur-2xl"/><img src={heroImage} alt="Doctor consulting with a patient" className="relative h-[390px] w-full rounded-[2rem] object-cover shadow-glow"/><div className="absolute bottom-5 left-5 rounded-2xl bg-white/95 p-4 shadow-lg backdrop-blur dark:bg-slate-900/95"><p className="text-xs font-semibold text-slate-500">Always here for you</p><p className="mt-1 text-sm font-bold text-slate-900 dark:text-white">24/7 emergency care</p></div></div></div></section>
 <section className="container-page grid grid-cols-2 gap-4 py-10 md:grid-cols-4">{stats.map(([n,l])=><div key={l} className="text-center"><p className="text-3xl font-bold text-brand-600">{n}</p><p className="mt-1 text-sm text-slate-500">{l}</p></div>)}</section>
 <section className="container-page py-12"><p className="text-sm font-bold uppercase tracking-widest text-brand-600">Our specialties</p><div className="mt-2 flex items-end justify-between"><h2 className="text-3xl font-bold text-slate-900">Care for every chapter of life</h2><Link className="hidden text-sm font-semibold text-brand-600 md:block" to="/services">View all services →</Link></div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{departments.map(([name,desc])=><article className="card" key={name}><div className="mb-4 inline-flex rounded-xl bg-blue-50 p-3 text-brand-600"><Stethoscope/></div><h3 className="font-bold text-slate-900">{name}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{desc}</p></article>)}</div></section>
 <section className="bg-slate-900 py-16 text-white"><div className="container-page"><p className="text-sm font-bold uppercase tracking-widest text-blue-300">Our specialists</p><h2 className="mt-2 text-3xl font-bold">Meet the people behind the care</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{doctors.map(d=><div key={d.name} className="rounded-2xl bg-white p-6 text-slate-900"><div className={`flex h-14 w-14 items-center justify-center rounded-full text-lg font-bold ${d.color}`}>{d.initials}</div><h3 className="mt-5 font-bold">{d.name}</h3><p className="mt-1 text-sm text-slate-500">{d.specialty}</p><Link to="/appointments" className="mt-5 inline-block text-sm font-semibold text-brand-600">Book consultation →</Link></div>)}</div></div></section>
 <section className="container-page py-16"><div className="rounded-3xl bg-brand-600 px-7 py-10 text-white md:flex md:items-center md:justify-between md:px-12"><div><h2 className="text-3xl font-bold">Need medical help today?</h2><p className="mt-3 text-blue-100">Book online in minutes, or call our 24-hour care team.</p></div><Link to="/appointments" className="mt-6 inline-flex rounded-lg bg-white px-5 py-3 font-semibold text-brand-600 md:mt-0">Book now</Link></div></section>
 </>}
