import { CalendarDays, CheckCircle2, Clock3, Mail, MapPin, Phone } from 'lucide-react'
import { Link } from 'react-router-dom'
import { departments, doctors } from '../../data/site'
const PageIntro = ({eyebrow,title,body}) => <section className="bg-brand-50 py-16"><div className="container-page max-w-3xl text-center"><p className="font-bold uppercase tracking-widest text-sm text-brand-600">{eyebrow}</p><h1 className="mt-3 text-4xl font-bold text-slate-900">{title}</h1><p className="mt-5 text-lg leading-8 text-slate-600">{body}</p></div></section>
export function AboutPage(){return <><PageIntro eyebrow="About MediCare" title="Medicine with a human touch" body="We combine clinical excellence and thoughtful service so every patient feels seen, heard, and supported."/><section className="container-page grid gap-10 py-16 md:grid-cols-2"><div><h2 className="text-3xl font-bold">Here when you need us most</h2><p className="mt-5 leading-7 text-slate-600">MediCare brings multidisciplinary expertise, modern facilities, and compassionate teams under one roof. Our care is coordinated around one simple idea: your wellbeing comes first.</p></div><div className="grid grid-cols-2 gap-4">{[['Expert team','Specialists across key disciplines'],['Patient first','Clear, caring communication'],['Always ready','24/7 emergency support'],['Modern care','Evidence-led clinical practice']].map(([a,b])=><div className="card" key={a}><CheckCircle2 className="text-brand-600"/><h3 className="mt-4 font-bold">{a}</h3><p className="mt-1 text-sm text-slate-500">{b}</p></div>)}</div></section></>}
export function ServicesPage(){return <><PageIntro eyebrow="Our services" title="Complete care, all in one place" body="From preventive care to complex treatment, our teams work together for better outcomes."/><section className="container-page grid gap-5 py-16 sm:grid-cols-2 lg:grid-cols-3">{departments.map(([name,desc])=><div className="card" key={name}><h2 className="text-lg font-bold">{name}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{desc}</p><Link className="mt-5 inline-block text-sm font-semibold text-brand-600" to="/appointments">Book a visit →</Link></div>)}</section></>}
export function DoctorsPage(){return <><PageIntro eyebrow="Find a specialist" title="Meet our experienced doctors" body="The right expertise and a listening ear—when you need both."/><section className="container-page grid gap-6 py-16 md:grid-cols-3">{doctors.map(d=><div className="card text-center" key={d.name}><div className={`mx-auto flex h-20 w-20 items-center justify-center rounded-full text-xl font-bold ${d.color}`}>{d.initials}</div><h2 className="mt-5 font-bold">{d.name}</h2><p className="mt-1 text-sm text-slate-500">{d.specialty}</p><Link className="btn-primary mt-5 w-full py-2 text-sm" to="/appointments">Book appointment</Link></div>)}</section></>}
export function AppointmentPage(){return <><PageIntro eyebrow="Appointments" title="Book a visit" body="Send us your preferred details and our reception team will confirm your appointment."/><section className="container-page max-w-2xl py-14"><form className="card grid gap-5 sm:grid-cols-2" onSubmit={e=>e.preventDefault()}>{[['Full name','text'],['Email address','email'],['Phone number','tel'],['Preferred date','date']].map(([name,type])=><label className="text-sm font-semibold" key={name}>{name}<input required type={type} className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-3 font-normal outline-none focus:border-brand-500" /></label>)}<label className="text-sm font-semibold sm:col-span-2">Reason for visit<textarea className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-3 font-normal outline-none focus:border-brand-500" rows="4"/></label><button className="btn-primary sm:col-span-2" type="submit"><CalendarDays className="mr-2" size={18}/> Request appointment</button></form></section></>}
export function ContactPage(){return <><PageIntro eyebrow="Contact us" title="We’re here to help" body="Reach out for appointments, service information, or urgent guidance."/><section className="container-page grid gap-5 py-16 md:grid-cols-3">{[[Phone,'Call us','+91 800 123 4567'],[Mail,'Email us','care@medicare.example'],[MapPin,'Visit us','12 Wellness Avenue, Your City']].map(([Icon,a,b])=><div className="card" key={a}><Icon className="text-brand-600"/><h2 className="mt-4 font-bold">{a}</h2><p className="mt-2 text-slate-500">{b}</p></div>)}</section></>}
export function NotFoundPage(){return <div className="container-page py-32 text-center"><p className="text-6xl font-bold text-brand-600">404</p><h1 className="mt-4 text-2xl font-bold">Page not found</h1><Link className="btn-primary mt-6" to="/">Back home</Link></div>}

